### ISSUE TITLE
Not working with QEMU parallel port emulation

### ISSUE THREAD

**Issue by vincentbernat** [pdewacht/adlipt#3]
Hey!

So, I am trying a first game and I get some odd results:

 - some notes are skipped
 - at the end of the intro, a note is still being played
 - I need to frequently reset the board to get correct sound again (otherwise pitch is wrong)

This could totally come from my unusual setup: I am using FreeDOS 1.2 (JEMM) over QEMU and a non-ISA parallel port on Linux. QEMU knows how to redirect a parallel port to a "physical" one (handled by a Linux driver). But maybe, it introduces timing issues. Or maybe Linux itself driving the parallel port introduces timing issues.

So, has someone already checked Indy3 on a more regular setup and should it be expected to work?

**Comment by pdewacht** [comment]
Do you mean this game? https://www.myabandonware.com/game/indiana-jones-and-the-last-crusade-the-graphic-adventure-1ba
It's not one I'm familiar with. I tried it on my test PC but I couldn't get it to work, it crashes with a "divide error".

I found that LucasArts issued a patch to deal with problems on fast systems (including sound problems), [see here](https://web.archive.org/web/20121107040406/http://www.lucasarts.com/support/update/indy-last.html) and [here](https://help.disney.com/articles/en_US/FAQ/List-of-updates-and-patches-for-Lucasfilm-games). The myabandonware version was already patched though, so it didn't help me. It might be useful to check that you have the patched version.

Have you tried the OPL2TEST program? Does that behave correctly? If that runs okay, you can try a game that's known to work, such as Commander Keen 4.

I know people have used FreeDOS/JEMM in VirtualBox on Windows, so virtualization shouldn't be a problem. What kind of non-ISA parallel port are you using? If it's a PCI card it should be fine. If it's [this thing](https://www-user.tu-chemnitz.de/~heha/basteln/PC/USB2LPT/index.en.htm) that might be a problem.

Hope this helps.

**Comment by vincentbernat** [comment]
Yes, this game. I get this result: https://www.youtube.com/watch?v=4qVuMQ7CPy4

I have downloaded the updated Indy256.exe and now, I get a divide by 0 each time I try to run it. So, it may be related. My goal at some point is to implement support in ScummVM, so I don't care much if this precise game works or not. I just have to check my board is working correctly. :) However, if you want to dig this particular problem, I can provide you with my "working" Indy256.exe.

I also tried the OPL2TEST program, but I am unsure what kind of sound I should expect. If I stop it and restart it, the sound is different each time. Maybe it's expected to have to press reset between each try. Do you have a sample online I could listen to check if everything is OK? I'll try Commander Keen to check if it sounds like in DOSbox.

The parallel port is a PCI Express one with a WCH chip. I didn't try with VirtualBox as I see no option for a parallel port.

Thanks for the help!

**Comment by pdewacht** [comment]
It should play the same every time... You can hear the music [in this video](https://www.youtube.com/watch?v=z3DU2mNBa6M&t=535s) at the 8:55 mark. If that doesn't work there's no point in trying games. Either there's something incompatible about your system or the OPL2LPT board is faulty.

Here are the VirtualBox instructions: [VIRTUALBOX_OPL2LPT.pdf](https://github.com/pdewacht/adlipt/files/1714892/VIRTUALBOX_OPL2LPT.pdf). I though these were linked on the serdashop.com page.

**Comment by pdewacht** [comment]
Actually, can you run this benchmark tool: https://2k38.be/adlipt/iospeed.exe
It will output something like this:
```
port                read   write
388h (adlib)      2021ns  2010ns
378h (lpt data)           1513ns
37Ah (lpt ctrl)   1546ns  1529ns
```
The numbers for `lpt data` and `lpt ctrl` should be at leat 600 or so nanoseconds. (Else the delays for the OPL2 chip will be too short. The joys of DOS programming.) This will be true for all 'real' parallel ports but maybe not in your setup.

(The `adlib` line is not relevant here.)

**Comment by vincentbernat** [comment]
So, the OPL2TEST.EXE doesn't sound like the video either. Despite a reset between each try, I always get a different result. Pitch and notes are missing. Mostly like with Indy3.

I have run your test program and I only get 85ns for read/write. So, I suppose that QEMU doesn't emulate the appropriate delays for a parallel port. I'll try with VirtualBox (or I'll try to patch QEMU).

Thanks again for the help!

**Comment by vincentbernat** [comment]
Hello,

On VirtualBox, this works just fine (with a non-updated INDY256.EXE).

I got 856ns/895ns for 388h (with the driver loaded).
I got 4710ns for 378h and 3027ns/2920ns for 37Ah.

Looking at the documentation [here](http://shipbrook.net/jeff/sb.html), it is said to wait 12 cycles. At 4.77 MHz, it would be 2508ns. It also says 3.3 µs (safety margin from AdLib?). Or read 6 time the register (meaning it takes 2 cycles to read the register?). With 856ns read, I am around 4 cycles for a read. I suppose for music, this doesn't matter much?

But if parallel port is slower behind, this would mean the driver will be busy writing to the parallel port for about 14 cycles. Since it almost matches the minimum 12 cycles to wait for, I suppose I am OK with this, right?

I suppose I'll have to read a bit the driver to know how the timing work.

**Comment by pdewacht** [comment]
Those iospeed numbers are weird. (adlib write should be much higher than lpt data.) It measures LPT1, maybe you have the OPL2LPT connected to a different port? Or perhaps VirtualBox does something weird.

Regarding OPL2 timing: The cycles in that document refer to the OPL2 clock. The OPL2 runs at 3.58 MHz, so 12 cycles is approximately 3.3 µs, and 84 cycles is 23 µs. The usual way to time such short durations on classic PCs is to use a bunch of dummy I/O operations, which normally take between ½ and 2 µs depending on the speed of the ISA bus.

Anyway, I wouldn't worry about timing if music now plays without glitches.

**Comment by vincentbernat** [comment]
The OPL2LPT is connected to LPT1. But yes, this works fine as is. I'll close the issue. Thanks again!

**Comment by sofakng** [comment]
I'm sorry to bring up this extremely old topic, but I can't find too much information on this.

Does a PCIe parallel port card + QEMU allow the OPL2LPT and OPL3LPT to work on Windows 10?  If so, how about the TNDLPT adapter?
