### ISSUE TITLE
opl2test/opl3test produce garbage output on 386sx-16 computers

### ISSUE THREAD

**Issue by MobyGamer** [pdewacht/adlipt#7]
I've been helping test and write code to support the OPL2LPT, based on the code found in OPL2TEST.  Out of all my test systems (which range from 4.77 MHz 8088 to a PPro 200), my 386sx-16 systems produce garbage output when running OPL2TEST or OPL3TEST (when tested on an OPL3LPT).  The same goes for patched games, or AdLIb games running the ADLIPT TSR... except one system (Dell 316sx), which works when ADLIPT is loaded and translating, but otherwise fails the same OPL2TEST test.

It is unlikely that all my 386sx-16 systems have bad parallel ports; they work with other devices, and the noise produced by opl2test is the same noise across all of them (ie. it is consistent).  What I think is happening is that there is some sort of timing issue with the strobe sequence sent to the control port that is somehow only detectable at that speed class.  However, I've been unable to figure out what that might be.  I've tried adding delays (through dummy JMP $+2 and OUT EE,AL instructions) as well as removing delays (unrolling IN AL,DX OPL2 settle time, removing it completely) and haven't found a solution.

My fear is that the code in OPL2TEST, control port strobe or otherwise, is not exactly correct for supporting the OPL2LPT device.  Is this a known issue?  If so, is there a workaround?

**Comment by MobyGamer** [comment]
I was just notified that sometimes a pullup resistor is required on the OPLxLPT hardware for compatibility with some systems.  I am going to apply that to my hardware and report back.

**Comment by MobyGamer** [comment]
The pullup resistor fix worked, so this issue can likely be closed.  I do find it interesting, however, that on one system, ADLIPT worked before the modification when nothing else did -- a happy timing accident, perhaps.

**Comment by squelch41** [comment]
Where did you put the pull up resistor and what value did you use? I am having a similar problem on a 386sx

**Comment by MobyGamer** [comment]
Can't find hardware at the moment, but you may want to contact serdaco, as they may have implemented it as a permanent fix on what they sell.
